//
// Created by peter tumulty on 7/12/22.
//

#ifndef AIRGEADBANKINGAPP_PRINTCONTINUEMESSAGE_H
#define AIRGEADBANKINGAPP_PRINTCONTINUEMESSAGE_H

void printContinueMessage();

#endif //AIRGEADBANKINGAPP_PRINTCONTINUEMESSAGE_H
